# Site
repository: wintrover/wintrover.github.io # 사용자님의 GitHub 저장소 경로
# favicon: images/favicon.ico # 필요시 파비콘 경로 지정

# Content configuration version
version: 2

# Personal info
name: Su Hyok Yun # 기존 title에서 가져옴
title: Software Developer # 예시 직함, 본인에 맞게 수정
email: your-email@example.com # 실제 이메일 주소로 변경해주세요.
# email_title: Email
# phone: Your phone number (optional)
# phone_title: Phone
website: https://wintrover.github.io # 기존 url에서 가져옴
# website_title: Web

# Dark Mode (true/false/never)
darkmode: never # 기본값 유지 또는 취향에 따라 변경

# Social links
# twitter_username:
github_username: wintrover # 사용자님의 GitHub ID
# stackoverflow_username:
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
# linkedin_username: # LinkedIn 사용자명 입력
# xing_username:
# pinterest_username:
# youtube_username:
# orcid_username:
# googlescholar_username:

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: assets/images/profile.jpg # 프로필 이미지 경로 예시, 실제 이미지 경로로 수정하거나 이미지를 추가해주세요.
about_content: | # Markdown 형식으로 자신을 소개해주세요.
  안녕하세요! Su Hyok Yun 입니다.
  이곳은 저의 개인 포트폴리오 웹사이트입니다.
  방문해주셔서 감사합니다.
  (이곳에 더 자세한 자기소개를 Markdown 형식으로 작성해주세요.)

content:
  - title: Projects # 기존 _projects 컬렉션 내용을 여기에 통합
    layout: list
    content:
      # _projects 폴더의 내용을 기반으로 아래 항목들을 채워주세요.
      # 예시:
      # - layout: left # 또는 top, right 등 테마가 지원하는 레이아웃
      #   title: 프로젝트 명칭 1
      #   # link: /projects/project-file-name-1 # 해당 프로젝트의 상세 페이지 링크 (필요시)
      #   # additional_links:
      #   #   - title: GitHub Repository
      #   #     icon: fab fa-github
      #   #     url: https://github.com/wintrover/project-repo-1
      #   quote: >
      #     프로젝트에 대한 간략한 한 줄 요약
      #   description: |
      #     - 프로젝트에서 수행한 역할 및 주요 기능
      #     - 사용 기술 스택
      #     - 성과 및 배운 점

  - title: Experience # 경력 사항
    layout: list
    content:
      # 경력 사항이 있다면 아래 형식으로 추가해주세요.
      # - layout: right
      #   title: 회사명
      #   sub_title: 직책
      #   caption: 근무 기간 (예: 2020.03 - 현재)
      #   # link: 회사 웹사이트 링크 (선택 사항)
      #   # quote: >
      #   #   회사에 대한 간략한 소개 (선택 사항)
      #   description: |
      #     - 담당했던 주요 업무 및 프로젝트
      #     - 사용했던 기술 및 도구
      #     - 구체적인 성과 (수치화 가능하면 좋음)

  - title: Education # 학력 사항
    layout: list
    content:
      # 학력 사항을 아래 형식으로 추가해주세요.
      # - layout: top-right
      #   title: 학교명
      #   sub_title: 전공 및 학위 (예: 컴퓨터공학 학사)
      #   caption: 재학 기간 (예: 2015.03 - 2019.02)
      #   # quote: >
      #   #   학교 또는 학과에 대한 간략한 소개 (선택 사항)
      #   description: |
      #     - 주요 학습 내용 및 수강 과목
      #     - 관련 프로젝트 또는 논문
      #     - 학점 또는 성적 (선택 사항)

  - title: Skills # 보유 기술
    layout: text # 또는 list 형식으로도 가능
    content: | # Markdown으로 자유롭게 기술
      **Programming Languages:**
      - Python
      - Java
      - JavaScript

      **Frameworks & Libraries:**
      - Spring Boot
      - React
      - Node.js

      **Databases:**
      - MySQL
      - PostgreSQL

      **Tools:**
      - Git & GitHub
      - Docker
      - Jenkins

      **(기타 본인이 자신있는 기술들을 추가해주세요)**

# Footer
footer_show_references: true
# references_title: References on request

# Build settings
# theme: modern-resume-theme # 로컬에서 직접 테마를 수정/개발하는 경우가 아니면 주석 처리
remote_theme: sproogen/modern-resume-theme # GitHub 호스팅 시 권장되는 방식

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-feed # 기존 플러그인 유지
 - jekyll-seo-tag # 기존 플러그인 유지

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
