# Site
repository: wintrover/wintrover.github.io
# favicon: /assets/favicon.ico

# Content configuration version
version: 2

# Personal info
# name, title, etc., are now primarily managed via _data/[lang]/strings.yml (e.g., site_title)
name: 윤수혁
title: ML / AI Application Developer
email: wintrover@gmail.com
homepage: wintrover.github.io
# email_title: Email
# phone: Your phone number (optional)
# phone_title: Phone
# website: https://wintrover.github.io
# website_title: Web
description: "AI·LLM·컴퓨터 비전 프로젝트를 다루는 윤수혁 개발자 포트폴리오"
image: "/assets/images/profile.png"
logo: "/assets/images/profile.png"

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username:
github_username: wintrover
# stackoverflow_username:
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: suhyok-yun-1934b713a
# xing_username:
# pinterest_username:
# youtube_username:
# orcid_username:
# googlescholar_username:

# Additional icon links
additional_links:
  - title: Blog
    icon: fab fa-blogger
    url: https://wintrover.github.io/blog

# Google Analytics and Tag Manager
# gtm: "GTM-0000000"
gtag: "G-99HN70355W"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: assets/images/profile.png
# about_content: is now managed by about_content_md in _data/[lang]/strings.yml

content:
  - title: Projects # This section title is now managed by section_title_projects in _data
    id: projects
    layout: list
    content:
      - layout: left
        id: cvfactory
        logo: assets/images/CVFactory_logo.png
        additional_links:
          - data_key_id: github
            icon: fab fa-github
            url: https://github.com/CV-Factory
          - data_key_id: demo
            icon: fas fa-external-link-alt
            url: https://cvfactory.dev
      - layout: left
        id: face_recognition_dating_app
        logo: assets/images/sodamyeon_logo.png
        additional_links:
          - data_key_id: github
            icon: fab fa-github
            url: https://github.com/Suyangdaekun/Sodamyeon.git
          - data_key_id: youtube_demo
            icon: fab fa-youtube
            url: https://www.youtube.com/embed/OM7OZrjQ1wo
      - layout: left
        id: deep_fake_detect_app
        logo: assets/images/bluecheck_logo.png
        additional_links:
          - data_key_id: github
            icon: fab fa-github
            url: https://github.com/wintrover/DeepFakeDetectApp
          - data_key_id: youtube_demo
            icon: fab fa-youtube
            url: https://www.youtube.com/embed/O3X-rWDxpi8

  - title: Experience # This section title is now managed by section_title_experience in _data
    id: experience
    layout: list
    content:
      - layout: left
        id: focc_inc
      - layout: left
        id: insight_marketing_labs
      - layout: left
        id: vizcam

  - title: Education # This section title is now managed by section_title_education in _data
    id: education
    layout: list
    content:
      - layout: left
        id: intel_ai_for_future_workforce
      - layout: left
        id: halla_university

  - title: Skills # This section title is now managed by section_title_skills in _data
    layout: text
    content: # Content is managed by skills_content_md in _data/[lang]/strings.yml

# Footer
footer_show_references: false
# references_title: References on request

# Build settings
# theme: modern-resume-theme # 로컬에서 직접 테마를 수정/개발하는 경우가 아니면 주석 처리
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-polyglot
 - jekyll-sitemap
 - jekyll-feed

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  "CODE_OF_CONDUCT.md",
  "CONTRIBUTING.md",
  "LICENSE",
  "modern-resume-theme.gemspec",
  "README.md",
  ]

url: "https://wintrover.github.io"
baseurl: ""

# jekyll-polyglot settings
languages: ["ko", "en"]
default_lang: "ko"
exclude_from_localization: ["assets/", "lib/"]
parallel_localization: false

# The following 'profile' section seems to be a duplicate or misconfigured,
# as 'name' is already defined at the top and should be handled by _data files.
# It should be reviewed or removed if redundant.
# profile:
#   name: "윤수혁"
