name: Deploy Jekyll site and Generate PDF

on:
  push:
    branches:
      - production # 저장소의 기본 브랜치명으로 수정 (예: master, main)
  workflow_dispatch: # 수동 실행 옵션

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for softprops/action-gh-release
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Matched with generate-pdf.yml
          bundler-cache: false # Enabled for efficiency

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --source . --destination _site --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      # --- PDF Generation Steps Start ---
      - name: Setup Node.js for Playwright
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Install Node.js dependencies for PDF script
        run: npm i playwright

      - name: Create PDF generation script
        run: |
          cat <<'EOF' > generate-pdf.js
          const { chromium } = require('playwright');
          const http = require('http');
          const fs = require('fs');
          const path = require('path');

          (async () => {
            console.log('Starting local server for PDF generation...');
            const server = http.createServer((req, res) => {
              let filePath = path.join(__dirname, '_site', req.url === '/' ? 'index.html' : req.url);
              let extname = path.extname(filePath);
              let contentType = 'text/html';
              switch (extname) {
                  case '.js': contentType = 'text/javascript'; break;
                  case '.css': contentType = 'text/css'; break;
                  case '.json': contentType = 'application/json'; break;
                  case '.png': contentType = 'image/png'; break;
                  case '.jpg': contentType = 'image/jpeg'; break;
                  case '.woff2': contentType = 'font/woff2'; break;
              }

              fs.readFile(filePath, (error, content) => {
                  if (error) {
                      if(error.code == 'ENOENT'){
                          res.writeHead(404, {'Content-Type': 'text/plain'});
                          res.end(`File not found: ${filePath}`);
                      } else {
                          console.error(`Error reading file ${filePath}:`, error);
                          res.writeHead(500, {'Content-Type': 'text/plain'});
                          res.end('Server error');
                      }
                  } else {
                      res.writeHead(200, { 'Content-Type': contentType });
                      res.end(content, 'utf-8');
                  }
              });
            }).listen(8080, () => console.log('Local server running on port 8080'));

            await new Promise(resolve => setTimeout(resolve, 2000));

            console.log('Starting PDF generation with Playwright...');
            const browser = await chromium.launch();
            const page = await browser.newPage();
            
            try {
              await page.goto('http://localhost:8080', { waitUntil: 'networkidle' });
              console.log('Page loaded successfully for PDF generation.');

              await page.emulateMedia({ media: 'print' });
              console.log('Emulating print media type.');
              
              await page.pdf({
                path: 'resume.pdf',
                format: 'A4',
                printBackground: true,
                margin: {
                  top: '1.5cm',
                  right: '1.5cm',
                  bottom: '1.5cm',
                  left: '1.5cm',
                }
              });
              console.log('Successfully generated resume.pdf');
            } catch (err) {
              console.error('An error occurred during Playwright PDF generation:', err);
              process.exit(1);
            } finally {
              await browser.close();
              server.close();
              console.log('Playwright browser and local server closed.');
            }
          })();
          EOF

      - name: Run Playwright script to generate PDF
        run: node generate-pdf.js
      
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}-${{ github.sha }}
          release_name: Release ${{ github.ref_name }}-${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resume.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf

      # --- PDF Generation Steps End ---

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
